package rest;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SecurityTokenOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string login = 2;
    /**
     * <code>required string login = 2;</code>
     */
    boolean hasLogin();
    /**
     * <code>required string login = 2;</code>
     */
    java.lang.String getLogin();
    /**
     * <code>required string login = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    // repeated string roles = 3;
    /**
     * <code>repeated string roles = 3;</code>
     */
    java.util.List<java.lang.String>
    getRolesList();
    /**
     * <code>repeated string roles = 3;</code>
     */
    int getRolesCount();
    /**
     * <code>repeated string roles = 3;</code>
     */
    java.lang.String getRoles(int index);
    /**
     * <code>repeated string roles = 3;</code>
     */
    com.google.protobuf.ByteString
        getRolesBytes(int index);

    // required int64 expires = 4;
    /**
     * <code>required int64 expires = 4;</code>
     */
    boolean hasExpires();
    /**
     * <code>required int64 expires = 4;</code>
     */
    long getExpires();
  }
  /**
   * Protobuf type {@code SecurityToken}
   */
  public static final class SecurityToken extends
      com.google.protobuf.GeneratedMessage
      implements SecurityTokenOrBuilder {
    // Use SecurityToken.newBuilder() to construct.
    private SecurityToken(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SecurityToken(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SecurityToken defaultInstance;
    public static SecurityToken getDefaultInstance() {
      return defaultInstance;
    }

    public SecurityToken getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SecurityToken(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              login_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                roles_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              roles_.add(input.readBytes());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              expires_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          roles_ = new com.google.protobuf.UnmodifiableLazyStringList(roles_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Auth.internal_static_SecurityToken_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Auth.internal_static_SecurityToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Auth.SecurityToken.class, Auth.SecurityToken.Builder.class);
    }

    public static com.google.protobuf.Parser<SecurityToken> PARSER =
        new com.google.protobuf.AbstractParser<SecurityToken>() {
      public SecurityToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SecurityToken(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SecurityToken> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string login = 2;
    public static final int LOGIN_FIELD_NUMBER = 2;
    private java.lang.Object login_;
    /**
     * <code>required string login = 2;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string login = 2;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          login_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string login = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string roles = 3;
    public static final int ROLES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList roles_;
    /**
     * <code>repeated string roles = 3;</code>
     */
    public java.util.List<java.lang.String>
        getRolesList() {
      return roles_;
    }
    /**
     * <code>repeated string roles = 3;</code>
     */
    public int getRolesCount() {
      return roles_.size();
    }
    /**
     * <code>repeated string roles = 3;</code>
     */
    public java.lang.String getRoles(int index) {
      return roles_.get(index);
    }
    /**
     * <code>repeated string roles = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRolesBytes(int index) {
      return roles_.getByteString(index);
    }

    // required int64 expires = 4;
    public static final int EXPIRES_FIELD_NUMBER = 4;
    private long expires_;
    /**
     * <code>required int64 expires = 4;</code>
     */
    public boolean hasExpires() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 expires = 4;</code>
     */
    public long getExpires() {
      return expires_;
    }

    private void initFields() {
      id_ = 0;
      login_ = "";
      roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      expires_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExpires()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLoginBytes());
      }
      for (int i = 0; i < roles_.size(); i++) {
        output.writeBytes(3, roles_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, expires_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLoginBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roles_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(roles_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getRolesList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, expires_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Auth.SecurityToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Auth.SecurityToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Auth.SecurityToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Auth.SecurityToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Auth.SecurityToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Auth.SecurityToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Auth.SecurityToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Auth.SecurityToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Auth.SecurityToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Auth.SecurityToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Auth.SecurityToken prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SecurityToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Auth.SecurityTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Auth.internal_static_SecurityToken_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Auth.internal_static_SecurityToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Auth.SecurityToken.class, Auth.SecurityToken.Builder.class);
      }

      // Construct using Auth.SecurityToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        login_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        expires_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Auth.internal_static_SecurityToken_descriptor;
      }

      public Auth.SecurityToken getDefaultInstanceForType() {
        return Auth.SecurityToken.getDefaultInstance();
      }

      public Auth.SecurityToken build() {
        Auth.SecurityToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Auth.SecurityToken buildPartial() {
        Auth.SecurityToken result = new Auth.SecurityToken(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.login_ = login_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          roles_ = new com.google.protobuf.UnmodifiableLazyStringList(
              roles_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.roles_ = roles_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.expires_ = expires_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Auth.SecurityToken) {
          return mergeFrom((Auth.SecurityToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Auth.SecurityToken other) {
        if (other == Auth.SecurityToken.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLogin()) {
          bitField0_ |= 0x00000002;
          login_ = other.login_;
          onChanged();
        }
        if (!other.roles_.isEmpty()) {
          if (roles_.isEmpty()) {
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRolesIsMutable();
            roles_.addAll(other.roles_);
          }
          onChanged();
        }
        if (other.hasExpires()) {
          setExpires(other.getExpires());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasLogin()) {
          
          return false;
        }
        if (!hasExpires()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Auth.SecurityToken parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Auth.SecurityToken) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string login = 2;
      private java.lang.Object login_ = "";
      /**
       * <code>required string login = 2;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string login = 2;</code>
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string login = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string login = 2;</code>
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string login = 2;</code>
       */
      public Builder clearLogin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>required string login = 2;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        login_ = value;
        onChanged();
        return this;
      }

      // repeated string roles = 3;
      private com.google.protobuf.LazyStringList roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRolesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          roles_ = new com.google.protobuf.LazyStringArrayList(roles_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public java.util.List<java.lang.String>
          getRolesList() {
        return java.util.Collections.unmodifiableList(roles_);
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public int getRolesCount() {
        return roles_.size();
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public java.lang.String getRoles(int index) {
        return roles_.get(index);
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRolesBytes(int index) {
        return roles_.getByteString(index);
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder setRoles(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder addRoles(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder addAllRoles(
          java.lang.Iterable<java.lang.String> values) {
        ensureRolesIsMutable();
        super.addAll(values, roles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder clearRoles() {
        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder addRolesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
        return this;
      }

      // required int64 expires = 4;
      private long expires_ ;
      /**
       * <code>required int64 expires = 4;</code>
       */
      public boolean hasExpires() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 expires = 4;</code>
       */
      public long getExpires() {
        return expires_;
      }
      /**
       * <code>required int64 expires = 4;</code>
       */
      public Builder setExpires(long value) {
        bitField0_ |= 0x00000008;
        expires_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 expires = 4;</code>
       */
      public Builder clearExpires() {
        bitField0_ = (bitField0_ & ~0x00000008);
        expires_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SecurityToken)
    }

    static {
      defaultInstance = new SecurityToken(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SecurityToken)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SecurityToken_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SecurityToken_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\"J\n\rSecurityToken\022\n\n\002id\030\001 \002(" +
      "\005\022\r\n\005login\030\002 \002(\t\022\r\n\005roles\030\003 \003(\t\022\017\n\007expir" +
      "es\030\004 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SecurityToken_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SecurityToken_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SecurityToken_descriptor,
              new java.lang.String[] { "Id", "Login", "Roles", "Expires", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
